
--CREATE LOGIN
CREATE LOGIN NewLogin WITH PASSWORD = '123456'

--RENAME LOGIN
ALTER LOGIN NewLogin WITH NAME = NewLogin2

--CHANGE LOGIN PASSWORD
ALTER LOGIN NewLogin2 WITH PASSWORD = '654321'

--DROP LOGIN
DROP LOGIN NewLogin2
